// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueApp.Data;

#nullable disable

namespace QueueAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueueApp.Models.Notification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("QueueEntryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("QueueEntryID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QueueApp.Models.QueueEntry", b =>
                {
                    b.Property<long>("QueueEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QueueEntryID"));

                    b.Property<int?>("CurrentPosition")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedWaitTime")
                        .HasColumnType("int")
                        .HasComment("Thời gian ước tính chờ (phút)");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<int>("QueueTypeID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QueueEntryID");

                    b.HasIndex("QueueTypeID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("UserID");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("QueueApp.Models.QueueType", b =>
                {
                    b.Property<int>("QueueTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueueTypeID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPartySize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("StandardServiceDuration")
                        .HasColumnType("int");

                    b.HasKey("QueueTypeID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("QueueTypes");
                });

            modelBuilder.Entity("QueueApp.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdminUserID")
                        .HasColumnType("int");

                    b.Property<string>("GooglePlaceID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OverallRating")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("RestaurantID");

                    b.HasIndex("AdminUserID")
                        .IsUnique()
                        .HasFilter("[AdminUserID] IS NOT NULL");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("QueueApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QueueApp.Models.Notification", b =>
                {
                    b.HasOne("QueueApp.Models.QueueEntry", "QueueEntry")
                        .WithMany("Notifications")
                        .HasForeignKey("QueueEntryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueueApp.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QueueEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueueApp.Models.QueueEntry", b =>
                {
                    b.HasOne("QueueApp.Models.QueueType", "QueueType")
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueueApp.Models.Restaurant", "Restaurant")
                        .WithMany("QueueEntries")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueueApp.Models.User", "User")
                        .WithMany("QueueEntries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QueueType");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueueApp.Models.QueueType", b =>
                {
                    b.HasOne("QueueApp.Models.Restaurant", "Restaurant")
                        .WithMany("QueueTypes")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("QueueApp.Models.Restaurant", b =>
                {
                    b.HasOne("QueueApp.Models.User", "AdminUser")
                        .WithOne("Restaurant")
                        .HasForeignKey("QueueApp.Models.Restaurant", "AdminUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("QueueApp.Models.QueueEntry", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("QueueApp.Models.QueueType", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("QueueApp.Models.Restaurant", b =>
                {
                    b.Navigation("QueueEntries");

                    b.Navigation("QueueTypes");
                });

            modelBuilder.Entity("QueueApp.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("QueueEntries");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
